name: "Restore cache"
description: "Install and cache node_modules"

inputs:
  world:
    description: "Local world folder name"
    required: false
    default: "example_1_hello_hiberworld"

runs:
  using: "composite"
  steps:
    # - name: Build
    #   shell: bash
    #   working-directory: ./${{ inputs.world }}
    #   env:
    #     SAVE_ON_CLOSE: true
    #   run: |
    #     pwd
    #     echo $SAVE_ON_CLOSE
    #     yarn
    #     yarn dev &
    #     sleep 10

    - name: "Generate scene.json"
      uses: ./.github/actions/open_url

    # - name: "Upload Screenshot"
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Screenshot
    #     path: ./${{ inputs.world }}/screenshot.png
    #     retention-days: 5

    # - name: "Upload scene.json"
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Scene
    #     path: ./${{ inputs.world }}/scene.json
    #     retention-days: 5

    # - name: Publish
    #   shell: bash
    #   working-directory: ./${{ inputs.world }}
    #   run: |
    #     pwd
    #     ls
    #     yarn upload --debug
