name: "Publish World"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache
        id: cache-dependencies

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

  Publish:
    name: Publish worlds
    runs-on: ubuntu-latest
    needs: Setup
    env:
      DEVELOPER_TOKEN: ${{ secrets.DEVELOPER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/publish
          with:
            world: 'example_1_hello_hiberworld'
